version: '3.2'

services:
     redmine:
          image: redmine
          restart: always
          container_name: redmine
          volumes:
               - ./redmine/files:/usr/src/redmine/files
               - ./redmine/plugins:/usr/src/redmine/plugins
               - ./redmine/themes:/usr/src/redmine/public/themes
          ports:
               - 3000:3000
          environment:
               REDMINE_DB_MYSQL: db
               REDMINE_DB_PASSWORD: redmine
               REDMINE_DB_DATABASE: redmine
               REDMINE_DB_ENCODING: utf8
     db:
          image: mysql
          restart: always
          ports:
               - 3306:3306
          volumes:
               - ./redmine/db:/var/lib/mysql
          environment:
               MYSQL_ROOT_PASSWORD: redmine
               MYSQL_DATABASE: redmine
          command:
               - --character-set-server=utf8mb4
               - --collation-server=utf8mb4_unicode_ci
